#!vm;utf-8
$response.setHeader("Cache-Control", "max-age=600")
/*
 * © UOL TAG MANAGER - Todos os direitos reservados
 * VERSÃO: 1.4.7
 */
if(!window.TM_VERSION_LOGGED){
    TM_VERSION_LOGGED = true;
    if(window.console){
        console.log('[UOL Tag Manager] VERSION: 1.4.7');
    }
}
#set($scriptPath = "." + $request.getParameter("ORIGINAL_PATH"))
(function (){
var TM = window.TM || {};
var adServer = 'dfp';
#if($scriptPath.indexOf("./h/") != "-1")
    #include("./js/src/dfp/gpt.js")
    #if($scriptPath.indexOf("./h/homeuol.js") != "-1" || $scriptPath.indexOf("./h/uol/home.js") != "-1")
        #include("./js/config/divs/home.js")
        #parse("./js/src/home/top.vm")
        #parse("./js/src/home/uol.vm")
        #parse("./js/src/home/bottom.vm")
    #elseif($scriptPath.indexOf("./h/bol/home.js") != "-1")
        #include("./js/config/divs/homebol.js")
        #parse("./js/src/home/top.vm")
        #parse("./js/src/home/bol.vm")
        #parse("./js/src/home/bottom.vm")
    #else
        #parse("./js/config/blacklist.vm")
        #if($scriptPath.indexOf("./h/uol/mobile.js") != "-1" || $scriptPath.indexOf("./h/mobile.js") != "-1" || $scriptPath.indexOf("./h/mobile/uol.js") != "-1" || $scriptPath.indexOf("./h/pd/mobile.js") != "-1" || $scriptPath.indexOf("./mobile/pd.js") != "-1" || $scriptPath.indexOf("./h/bol/mobile.js") != "-1" || $scriptPath.indexOf("./h/par/mobile/shopping.js") != "-1")
            #include("./js/config/map/mobile.js")
            #include("./js/config/divs/mobile.js")
            #parse("./js/src/commons.vm")
            #parse("./js/src/mobile/display-mobile.vm")
            #parse("./js/src/init.vm")
            #parse("./js/behavioral/bt-track.vm")
        #elseif($scriptPath.indexOf("./h/folha/mobile.js") != "-1" || $scriptPath.indexOf("./mobile/folha.js") != "-1")
            #include("./js/config/map/mobile-folha.js")
            #include("./js/config/divs/mobile.js")
            #parse("./js/src/commons.vm")
            #parse("./js/src/mobile/display-mobile.vm")
            #parse("./js/src/init.vm")
            #parse("./js/behavioral/bt-track.vm")
        #elseif($scriptPath.indexOf("./h/par/mobile.js") != "-1" || $scriptPath.indexOf("./mobile/par.js") != "-1")
            #include("./js/config/map/mobile-par.js")
            #include("./js/config/divs/mobile.js")
            #parse("./js/src/commons.vm")
            #parse("./js/src/mobile/display-mobile.vm")
            #parse("./js/src/init.vm")
            #parse("./js/behavioral/bt-track.vm")
        #else
            #if($scriptPath.indexOf("./h/uol/") != "-1")
                #include("./js/config/divs/default.js")
                #if($scriptPath.indexOf("shopping") != "-1")
                    #include("./js/config/map/par.js")
                    #include("./js/config/divs/par.js")
                    #parse("./js/src/display-par.vm")
                    #parse("./js/src/display-full.vm") 
                #else
                    #include("./js/config/map/uol.js")
                    #include("./js/config/divs/uol.js")
                    #parse("./js/src/commons.vm")
                    #if ($scriptPath.indexOf("mulher.js") != "-1")
                        #include("./js/config/cliques/uol.js")
                        #include("./js/src/cliques/adrequisitor.js")
                    #end
                    #parse("./js/src/display-full.vm")
                #end
            #elseif($scriptPath.indexOf("./h/pd/") != "-1")
                #include("./js/config/divs/default.js")
                #include("./js/config/map/uol.js")
                #include("./js/config/divs/pd.js")
                #parse("./js/src/commons.vm")
                #parse("./js/src/display-full.vm")
            #elseif($scriptPath.indexOf("./h/par/shopping.js") != "-1" || $scriptPath.indexOf("./h/par/catapreco.js") != "-1")
                #include("./js/config/divs/default.js")
                #include("./js/config/map/shopping.js")
                #include("./js/config/divs/shopping.js")
                #parse("./js/src/commons.vm")
                #parse("./js/src/display-full.vm")
            #elseif($scriptPath.indexOf("./h/par/todaoferta.js") != "-1")
                #include("./js/config/divs/default.js")
                #include("./js/config/map/todaoferta.js")
                #include("./js/config/divs/todaoferta.js")
                #parse("./js/src/commons.vm")
                #parse("./js/src/display-full.vm")
            #elseif($scriptPath.indexOf("./h/par/folha.js") != "-1")
                #include("./js/config/divs/default.js")
                #include("./js/config/map/folha.js")
                #include("./js/config/divs/folha.js")
                #parse("./js/src/commons.vm")
                #parse("./js/src/display-full.vm")
            #elseif($scriptPath.indexOf("./h/par/uolinvest.js") != "-1" || $scriptPath.indexOf("./h/par/uolnamoro.js") != "-1")
                #include("./js/config/divs/default.js")
                #include("./js/config/map/uol.js")
                #include("./js/config/divs/par.js")
                #parse("./js/src/commons.vm")
                #parse("./js/src/display-full.vm")
            #elseif($scriptPath.indexOf("./h/par/xpg.js") != "-1")
                #include("./js/config/divs/default.js")
                #include("./js/config/map/par-xpg.js")
                #include("./js/config/divs/par.js")
                #parse("./js/src/commons.vm")
                #parse("./js/src/display-full.vm")
            #elseif($scriptPath.indexOf("./h/par/") != "-1")
                #include("./js/config/divs/default.js")
                #include("./js/config/map/par.js")
                #include("./js/config/divs/par.js")
                #parse("./js/src/display-par.vm")
            #elseif($scriptPath.indexOf("./h/aff/") != "-1")
                #include("./js/config/divs/default.js")
                #include("./js/config/map/aff.js")
                #include("./js/config/divs/aff.js")
                #parse("./js/src/display-aff.vm")
            #end
            #parse("./js/src/init.vm")
        #end
    #end
#elseif($scriptPath.indexOf("./b/") != "-1")
    #if($scriptPath.indexOf("./par/sephora.js") != "-1")
        TM.retartgetingPartner = 'sephora';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
    #elseif($scriptPath.indexOf("./par/netshoes.js") != "-1")
        TM.retartgetingPartner = 'uol_netshoes';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
        #include("./js/src/utils/logs.js")
        #include("./js/src/utils/domUtils.js")
        #include("./js/src/utils/tagUtils.js")
        #include("./js/src/utils/objectUtils.js")
        #include("./js/src/dynad/dynad-track.js")
    #elseif($scriptPath.indexOf("./par/dafiti.js") != "-1")
        TM.retartgetingPartner = 'dafiti';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
        #include("./js/src/utils/logs.js")
        #include("./js/src/utils/domUtils.js")
        #include("./js/src/utils/tagUtils.js")
        #include("./js/src/utils/objectUtils.js")
        #include("./js/src/dynad/dynad-track.js")
    #elseif($scriptPath.indexOf("./par/dell.js") != "-1")
        TM.retartgetingPartner = 'dell';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
    #elseif($scriptPath.indexOf("./b/uol/barrauol.js") != "-1")
        #parse("./js/behavioral/bt-track.vm")
    #elseif($scriptPath.indexOf("./par/netflix.js") != "-1")
        TM.retartgetingPartner = 'netflix';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
    #elseif($scriptPath.indexOf("./par/cyrela.js") != "-1")
        TM.retartgetingPartner = 'cyrela';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
    #elseif($scriptPath.indexOf("./par/fastshop.js") != "-1")
        TM.retartgetingPartner = 'fastshop';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")       
        #include("./js/config/dynad/default.js")
        #include("./js/src/utils/logs.js")
        #include("./js/src/utils/domUtils.js")
        #include("./js/src/utils/tagUtils.js")
        #include("./js/src/utils/objectUtils.js")
    #elseif($scriptPath.indexOf("./par/even.js") != "-1")
        TM.retartgetingPartner = 'even';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")       
        #include("./js/config/dynad/default.js")
    #elseif($scriptPath.indexOf("./par/kanui.js") != "-1")
        TM.retartgetingPartner = 'kanui';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
        #include("./js/src/utils/logs.js")
        #include("./js/src/utils/domUtils.js")
        #include("./js/src/utils/tagUtils.js")
        #include("./js/src/utils/objectUtils.js")
        #include("./js/src/dynad/dynad-track.js")
    #elseif($scriptPath.indexOf("./par/pank.js") != "-1")
        TM.retartgetingPartner = 'pank';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
    #else
        #parse("./js/behavioral/bt-track.vm")
    #end
#elseif($scriptPath.indexOf("./par/") != "-1")
    #if($scriptPath.indexOf("./par/sephora.js") != "-1")
        TM.retartgetingPartner = 'sephora';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
    #elseif($scriptPath.indexOf("./par/netshoes.js") != "-1")
        TM.retartgetingPartner = 'uol_netshoes';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
        #include("./js/src/utils/logs.js")
        #include("./js/src/utils/domUtils.js")
        #include("./js/src/utils/tagUtils.js")
        #include("./js/src/utils/objectUtils.js")
        #include("./js/src/dynad/dynad-track.js")
    #elseif($scriptPath.indexOf("./par/dafiti.js") != "-1")
        TM.retartgetingPartner = 'dafiti';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
        #include("./js/src/utils/logs.js")
        #include("./js/src/utils/domUtils.js")
        #include("./js/src/utils/tagUtils.js")
        #include("./js/src/utils/objectUtils.js")
        #include("./js/src/dynad/dynad-track.js")
    #elseif($scriptPath.indexOf("./par/dell.js") != "-1")
        TM.retartgetingPartner = 'dell';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
    #elseif($scriptPath.indexOf("./b/uol/barrauol.js") != "-1")
        #parse("./js/behavioral/bt-track.vm")
    #elseif($scriptPath.indexOf("./par/netflix.js") != "-1")
        TM.retartgetingPartner = 'netflix';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
    #elseif($scriptPath.indexOf("./par/cyrela.js") != "-1")
        TM.retartgetingPartner = 'cyrela';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
    #elseif($scriptPath.indexOf("./par/fastshop.js") != "-1")
        TM.retartgetingPartner = 'fastshop';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")       
        #include("./js/config/dynad/default.js")
        #include("./js/src/utils/logs.js")
        #include("./js/src/utils/domUtils.js")
        #include("./js/src/utils/tagUtils.js")
        #include("./js/src/utils/objectUtils.js")
    #elseif($scriptPath.indexOf("./par/even.js") != "-1")
        TM.retartgetingPartner = 'even';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")       
        #include("./js/config/dynad/default.js")
    #elseif($scriptPath.indexOf("./par/kanui.js") != "-1")
        TM.retartgetingPartner = 'kanui';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
        #include("./js/src/utils/logs.js")
        #include("./js/src/utils/domUtils.js")
        #include("./js/src/utils/tagUtils.js")
        #include("./js/src/utils/objectUtils.js")
        #include("./js/src/dynad/dynad-track.js")
    #elseif($scriptPath.indexOf("./par/pank.js") != "-1")
        TM.retartgetingPartner = 'pank';
        #parse("./js/behavioral/retargeting.vm")
        #parse("./js/behavioral/bt-track.vm")
        #include("./js/config/dynad/default.js")
    #else
        #parse("./js/behavioral/bt-track.vm")
    #end
#elseif($scriptPath.indexOf("./test/") != "-1")
    #include("./js/config/map/uol.js")
    #include("./js/config/divs/default.js")
    #include("./js/config/divs/uol.js")
    #parse("./js/src/commons.vm")
    #if($scriptPath.indexOf("./test/cliques.js") != "-1")   
        #include("./js/config/cliques/test-default.js")
        #include("./js/src/cliques/adrequisitor.js")
    #elseif($scriptPath.indexOf("./test/cliques-custom.js") != "-1")    
        #include("./js/config/cliques/test-with-properties.js")
        #include("./js/src/cliques/adrequisitor.js")
    #end
    #parse("./js/src/display-full.vm")
    #parse("./js/src/init.vm")
#end
}());